# Generated by Django 5.1.2 on 2024-10-15 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombamento', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
                ('sistema_operacional', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tombamento', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='equipamentos.computador')),
            ],
        ),
    ]
