# Generated by Django 5.1.2 on 2024-10-15 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='usuarios.setor'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manutencoes', to='equipamentos.equipamento'),
        ),
        migrations.AddField(
            model_name='computador',
            name='memoria_interna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computadores', to='equipamentos.memoriainterna'),
        ),
        migrations.AddField(
            model_name='computador',
            name='memoria_ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computadores', to='equipamentos.memoriaram'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='equipamentos.monitor'),
        ),
        migrations.AddField(
            model_name='computador',
            name='placa_mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computadores', to='equipamentos.placamae'),
        ),
        migrations.AddField(
            model_name='computador',
            name='processador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computadores', to='equipamentos.processador'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='teclado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='equipamentos.teclado'),
        ),
    ]
