# Generated by Django 5.1.2 on 2024-10-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_initial'),
        ('usuarios', '0002_rename_codigo_servidor_inscricao_institucional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='computador',
            name='memoria_interna',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='memoria_ram',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='placa_mae',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='processador',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='computador',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='teclado',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='setor',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='marca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='plaqueta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='sala',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='servidor',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.servidor'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='situacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.servidor'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='equipamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.tipoequipamento'),
        ),
        migrations.DeleteModel(
            name='MemoriaInterna',
        ),
        migrations.DeleteModel(
            name='MemoriaRam',
        ),
        migrations.DeleteModel(
            name='PlacaMae',
        ),
        migrations.DeleteModel(
            name='Processador',
        ),
        migrations.DeleteModel(
            name='Computador',
        ),
        migrations.DeleteModel(
            name='Monitor',
        ),
        migrations.DeleteModel(
            name='Teclado',
        ),
    ]
