# Generated by Django 5.1.2 on 2024-10-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_tipoequipamento_remove_computador_memoria_interna_and_more'),
        ('usuarios', '0002_rename_codigo_servidor_inscricao_institucional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='servidor',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.servidor'),
        ),
    ]
