# Generated by Django 5.1.2 on 2024-10-16 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_alter_equipamento_options_alter_manutencao_options_and_more'),
        ('usuarios', '0004_alter_agencia_options_alter_servidor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='estado',
            field=models.CharField(choices=[('DEFASADO', 'Defasado'), ('ATENÇÃO', 'Atenção'), ('BOM', 'Boas condições'), ('NOVO', 'Como novo')], default='FUNCIONAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.servidor'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='situacao',
            field=models.CharField(choices=[('EM_USO', 'Em uso'), ('RESERVA', 'Na reserva'), ('MANUTENCAO', 'Em manutenção'), ('BAIXA', 'Deu baixa'), ('ALIENACAO', 'Transferido'), ('PERDIDO', 'Perdido'), ('ROUBADO', 'Roubado')], default='ATIVO', max_length=255),
        ),
    ]
