# Generated by Django 5.1.2 on 2024-10-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_alter_equipamento_estado_alter_equipamento_servidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
