# Generated by Django 5.1.2 on 2024-10-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_tipoequipamento_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutencao',
            name='data',
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='estado',
            field=models.CharField(choices=[('DEFASADO', 'Defasado'), ('ATENÇÃO', 'Atenção'), ('BOM', 'Boas condições'), ('NOVO', 'Como novo')], default='NOVO', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='situacao',
            field=models.CharField(choices=[('EM_USO', 'Em uso'), ('RESERVA', 'Na reserva'), ('MANUTENCAO', 'Em manutenção'), ('BAIXA', 'Deu baixa'), ('ALIENACAO', 'Transferido'), ('PERDIDO', 'Perdido'), ('ROUBADO', 'Roubado')], default='EM_USO', max_length=255),
        ),
    ]
