# Generated by Django 5.1.2 on 2024-10-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0008_remove_manutencao_data_manutencao_data_fim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutencao',
            old_name='data_inicio',
            new_name='data_ini',
        ),
    ]
