# Generated by Django 5.1.2 on 2024-10-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0009_rename_data_inicio_manutencao_data_ini'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutencao',
            old_name='data_ini',
            new_name='data_inicio',
        ),
    ]
