# Generated by Django 5.1.2 on 2024-10-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0010_rename_data_ini_manutencao_data_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
                ('tamanho_mem', models.IntegerField(blank=True, null=True)),
                ('n_serie', models.CharField(blank=True, max_length=255, null=True)),
                ('data_aquisicao', models.DateField()),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Componente',
                'verbose_name_plural': 'Tipos de Componentes',
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='EquipComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.ManyToManyField(to='equipamentos.componente')),
                ('equip', models.ManyToManyField(to='equipamentos.equipamento')),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.tipocomponente'),
        ),
    ]
