# Generated by Django 5.1.2 on 2024-10-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0011_componente_tipocomponente_equipamento_data_aquisicao_and_more'),
        ('usuarios', '0005_rename_id_agencia_setor_agencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutencao',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.setor'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.tipocomponente'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.tipoequipamento'),
        ),
    ]
