# Generated by Django 5.1.2 on 2024-11-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0012_remove_manutencao_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='componentes',
            field=models.ManyToManyField(null=True, to='equipamentos.componente'),
        ),
        migrations.DeleteModel(
            name='EquipComponente',
        ),
    ]
