# Generated by Django 5.1.2 on 2024-11-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0013_equipamento_componentes_delete_equipcomponente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='componentes',
            field=models.ManyToManyField(to='equipamentos.componente'),
        ),
    ]
