# Generated by Django 5.1.2 on 2024-11-08 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0014_alter_equipamento_componentes'),
        ('usuarios', '0012_remove_servidor_setor_setor_servidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='servidor',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='servidor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_responsaveis', to='usuarios.servidor'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='equipamentos.tipocomponente'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='componentes',
            field=models.ManyToManyField(related_name='equipamentos', to='equipamentos.componente'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='plaqueta',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='usuarios.setor'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='equipamentos.tipoequipamento'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='equipamentos.equipamento'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='usuarios.servidor'),
        ),
    ]
