# Generated by Django 5.1.2 on 2024-10-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servidor',
            old_name='codigo',
            new_name='inscricao_institucional',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='codigo_agencia',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='id_servidor',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='nome_setor',
        ),
        migrations.AddField(
            model_name='agencia',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.setor'),
        ),
        migrations.AddField(
            model_name='setor',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='id_agencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.agencia'),
        ),
    ]
