# Generated by Django 5.1.2 on 2024-10-15 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencia',
            options={'verbose_name': 'Agência', 'verbose_name_plural': 'Agências'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='id_agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.agencia'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
