# Generated by Django 5.1.2 on 2024-10-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_agencia_options_alter_servidor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setor',
            old_name='id_agencia',
            new_name='agencia',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='estado',
        ),
        migrations.AddField(
            model_name='servidor',
            name='chefe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
