# Generated by Django 5.1.2 on 2024-10-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_id_agencia_setor_agencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('ATENDIDO', 'Atendido'), ('ANALISE', 'Em analise'), ('NEGADO', 'Negado'), ('ENCAMINHADO', 'Encaminhado')], default='ANALISE', max_length=255),
        ),
    ]
