# Generated by Django 5.1.2 on 2024-10-24 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_solicitacao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_servidor',
        ),
        migrations.AddField(
            model_name='servidor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
