# Generated by Django 5.1.2 on 2024-11-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_user_is_admin_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='justificativa',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.servidor'),
        ),
    ]
