# Generated by Django 5.1.2 on 2024-11-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_servidor_usuario_solicitacao_justificativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='justificativa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
