# Generated by Django 5.1.2 on 2024-11-08 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_solicitacao_justificativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='chefe',
        ),
        migrations.AddField(
            model_name='setor',
            name='chefe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chefe_do_setor', to='usuarios.servidor'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores', to='usuarios.setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='usuarios.agencia'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('ATENDIDO', 'Atendido'), ('ANALISE', 'Em análise'), ('NEGADO', 'Negado'), ('ENCAMINHADO', 'Encaminhado')], default='ANALISE', max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.servidor'),
        ),
    ]
