# Generated by Django 5.1.2 on 2024-11-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_servidor_chefe_setor_chefe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='setor',
        ),
        migrations.AddField(
            model_name='setor',
            name='servidores',
            field=models.ManyToManyField(related_name='setores_associados', to='usuarios.servidor'),
        ),
    ]
